name: aso_cuda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - tsfresh=0.20.3
  - imbalanced-learn=0.12.4
  - scikit-learn=1.5.2
  - corner=2.2.2
  - joblib=1.4.2
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - statsmodels=0.14.2
  - pip
  - pip:
    - xgboost==2.1.2
    - lightgbm==4.5.0
    - catboost==1.2.7